class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror5'
        self.UnzipMirrorCommand = 'unzip5'
        self.TarMirrorCommand = 'tar5'
        self.CancelMirror = 'cancel5'
        self.CancelAllCommand = 'cancelall5'
        self.ListCommand = 'search'
        self.StatusCommand = 'status5'
        self.AuthorizedUsersCommand = 'users5'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart5'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help5'
        self.LogCommand = 'log5'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone5'
        self.CountCommand = 'count5'
        self.WatchCommand = 'watch5'
        self.TarWatchCommand = 'tarwatch5'
        self.DeleteCommand = 'del5'
        self.UsageCommand = 'usage5'
        self.MediaInfoCommand = 'mediainfo5'
        self.ConfigMenuCommand = 'config5'
        self.ShellCommand = 'shell5'
        self.UpdateCommand = 'update5'
        self.ExecHelpCommand = 'exechelp5'
        self.TsHelpCommand = 'tshelp5'

BotCommands = _BotCommands()
